### ISSUE TITLE
上传失败：StatusCodeError400

### ISSUE THREAD

**Issue by cyddgh** [Redns/picgo-plugin-NutStore#2]
尝试了账号密码和坚果云内的应用密码，都出现上传失败。请问如何解决？谢谢
![image](https://user-images.githubusercontent.com/10444611/160249468-3aa0a06c-0715-40ea-b0a5-4126a4985f2c.png)

**Comment by Redns** [comment]
您好，能否将 `picgo` 日志文件贴出来，`Windows` 用户的日志文件路径为 `C:\Users\{用户名}\AppData\Roaming\picgo\picgo.log`

**Comment by A-little-bit-of-data** [comment]
> 

2022-03-31 11:19:49 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 400 - "{\"errorCode\":\"IllegalArgument\",\"detailMsg\":\"the SHA256 hash value is not valid\",\"payload\":null}"
    at new StatusCodeError (D:\实用软件\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\实用软件\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\实用软件\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\实用软件\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\实用软件\PicGo\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\实用软件\PicGo\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)

我和楼主的错一样   借个楼

**Comment by Redns** [comment]
您好，能否将坚果云的配置界面贴出，我试了几次都不能重现 `Bug`
```
2022-03-31 20:57:21 [PicGo INFO] Before transform 
2022-03-31 20:57:21 [PicGo INFO] Transforming... Current transformer is [path] 
2022-03-31 20:57:21 [PicGo INFO] Before upload 
2022-03-31 20:57:21 [PicGo INFO] beforeUploadPlugins: autobackup running 
2022-03-31 20:57:21 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-03-31 20:57:21 [PicGo INFO] Uploading... Current uploader is [NutStore] 
2022-03-31 20:57:22 [PicGo INFO] afterUploadPlugins: autobackup running 
2022-03-31 20:57:22 [PicGo SUCCESS] 
https://www.jianguoyun.com/c/dl-file/2022331205721.jpeg?dt=r9m1ey&kv=bGppbmc0MzFAMTYzLmNvbQ&sd=ct2tt&ud=MiNSlkKBXRsOnhn8-gPvKNvmO40EZC9sGoYUHhuIdAs&vr=1 
```

**Comment by A-little-bit-of-data** [comment]
> 您好，能否将坚果云的配置界面贴出，我试了几次都不能重现 `Bug`
> 
> ```
> 2022-03-31 20:57:21 [PicGo INFO] Before transform 
> 2022-03-31 20:57:21 [PicGo INFO] Transforming... Current transformer is [path] 
> 2022-03-31 20:57:21 [PicGo INFO] Before upload 
> 2022-03-31 20:57:21 [PicGo INFO] beforeUploadPlugins: autobackup running 
> 2022-03-31 20:57:21 [PicGo INFO] beforeUploadPlugins: renameFn running 
> 2022-03-31 20:57:21 [PicGo INFO] Uploading... Current uploader is [NutStore] 
> 2022-03-31 20:57:22 [PicGo INFO] afterUploadPlugins: autobackup running 
> 2022-03-31 20:57:22 [PicGo SUCCESS] 
> https://www.jianguoyun.com/c/dl-file/2022331205721.jpeg?dt=r9m1ey&kv=bGppbmc0MzFAMTYzLmNvbQ&sd=ct2tt&ud=MiNSlkKBXRsOnhn8-gPvKNvmO40EZC9sGoYUHhuIdAs&vr=1 
> ```

![image](https://user-images.githubusercontent.com/31812278/161203031-a9b47545-c60f-4ee5-aec8-8a7a8423e792.png)
您好  我的是这种的，那两都是手动获取的，最后一个获取不到，麻烦看看是哪里的问题，另外我也是每次登录有微信验证码的那种，这种怎么解决？
谢谢！

**Comment by A-little-bit-of-data** [comment]
> > 您好，能否将坚果云的配置界面贴出，我试了几次都不能重现 `Bug`
> > ```
> > 2022-03-31 20:57:21 [PicGo INFO] Before transform 
> > 2022-03-31 20:57:21 [PicGo INFO] Transforming... Current transformer is [path] 
> > 2022-03-31 20:57:21 [PicGo INFO] Before upload 
> > 2022-03-31 20:57:21 [PicGo INFO] beforeUploadPlugins: autobackup running 
> > 2022-03-31 20:57:21 [PicGo INFO] beforeUploadPlugins: renameFn running 
> > 2022-03-31 20:57:21 [PicGo INFO] Uploading... Current uploader is [NutStore] 
> > 2022-03-31 20:57:22 [PicGo INFO] afterUploadPlugins: autobackup running 
> > 2022-03-31 20:57:22 [PicGo SUCCESS] 
> > https://www.jianguoyun.com/c/dl-file/2022331205721.jpeg?dt=r9m1ey&kv=bGppbmc0MzFAMTYzLmNvbQ&sd=ct2tt&ud=MiNSlkKBXRsOnhn8-gPvKNvmO40EZC9sGoYUHhuIdAs&vr=1 
> > ```
> 
> ![image](https://user-images.githubusercontent.com/31812278/161203031-a9b47545-c60f-4ee5-aec8-8a7a8423e792.png) 您好 我的是这种的，那两都是手动获取的，最后一个获取不到，麻烦看看是哪里的问题，另外我也是每次登录有微信验证码的那种，这种怎么解决？ 谢谢！

![image](https://user-images.githubusercontent.com/31812278/161204414-4f650247-f3ad-41ea-889c-2b1da6f49adc.png)

![image](https://user-images.githubusercontent.com/31812278/161204508-60c81e75-73a0-4a74-a3cb-68a6408c4a36.png)
然后上传我这会先后弹出这两个弹窗。

**Comment by Redns** [comment]
可以关闭坚果云的微信验证试下，[点这里](https://www.jianguoyun.com/#/safety)：
![安全选项](http://jing-image.test.upcdn.net/20220401141823.png)

**Comment by A-little-bit-of-data** [comment]
> 可以关闭坚果云的微信验证试下，[点这里](https://www.jianguoyun.com/#/safety)： ![安全选项](https://camo.githubusercontent.com/84005a4eebb2c97485fd4ad064f88caee90954ee3a0c4c4580d4789b7be56d73/687474703a2f2f6a696e672d696d6167652e746573742e757063646e2e6e65742f32303232303430313134313832332e706e67)

现在可以了，上传成功了，然后markdown也能用了，就是有点担心后期跟gitee一样搞骚操作

**Comment by cyddgh** [comment]
谢谢。现在才看到留言。
